#!/bin/bash

# TODO Determine which camera is which

# Set directories
declare -r bin=$(readlink -m "$(dirname "${BASH_SOURCE[0]}")")
declare -r share=$(readlink -m "$bin/../share/robot")
declare -r var="/var/local/robot"

# Set video configuration
declare -r threshold="0.15"
declare -r cap_fps="15/1"
declare -r bitrate=500000
declare -r stream_fps="5/1"
declare -r stream_width="432"
declare -r stream_height="240"
declare -r iframe="2500" # in ms

# Determine IP addresses to use
declare -r netdev="eth0"
declare oi_ip
declare robot_ip
if ip address show dev "$netdev" | grep -q 'inet 192.168.0'; then
    # Development environment
    oi_ip="192.168.0.51"
    #oi_ip="192.168.0.56"
    robot_ip="127.0.0.1"
else
    # Field environment
    oi_ip="10.15.19.5"
    robot_ip="10.15.19.2"
fi

# Set file locations
declare -r -a cfg_files=("$share/obj.data" "$share/tiny-yolo-obj.cfg" "$share/tiny-yolo-obj.backup")
declare -r timestamp=$(date --iso-8601=seconds)
declare -r video="$var/capture-$timestamp.avi"
declare -r datalog="$var/datalog-$timestamp.csv"
declare -r netlog="$var/network-$timestamp.csv"

# Start the network logger
"$bin"/netlog "$netdev" "$netlog" &

# Enable core dump collection
ulimit -c unlimited

# Run robot vision program
cd "$share"
"$bin"/robot --gpu 0 --thresh "$threshold" --fps "$cap_fps" --stream-width "$stream_width" --stream-height "$stream_height" --stream-fps "$stream_fps" --bitrate "$bitrate" --iframe "$iframe" --oper-ip "$oi_ip" --robot-ip "$robot_ip" --video "$video" --data-log "$datalog" "${cfg_files[@]}"
