#!/bin/bash

declare -r bin=$(readlink -f "$(dirname "${BASE_SOURCE[0]}")")
declare -r share=$(readlink -f "$bin/../share")
declare -r var="/var/local/robot"

declare -r threshold="0.15"
declare -r bitrate=750000
declare -r cap_fps="15/1"
declare -r stream_fps="15/1"
declare -r oi_ip="10.15.19.5"
declare -r robot_ip="10.15.19.2"
declare -r -a cfg_files="$share/robot/obj.data $share/tiny-yolo-obj2.cfg $share/tiny-yolo-obj2_4600.weights"
declare -r timestamp=$(date --iso-8601=seconds)
declare -r video="/var/local/robot/capture-$timestamp.avi"
declare -r datalog="/var/local/robot/datalog-$tmpstamp.cvs"

# TODO update from latest AI network

ulimit -c unlimited
"$bin"/robot --thresh "$threshold" --fps "$cap_fps" --stream-fps "$stream_fps" --bitrate "$bitrate" --ip "$oi_ip" --data-ip "$robot_ip" --video "$video" --data-log "$datalog" "$cfg_files[@]}"
