#!/bin/bash

declare -a make_args=(-j$(($(nproc) + 2)))
declare sudo
declare ip
if [[ $(hostname) == robin ]]; then
    make_args+=(GPU=0 CUDNN=0)
    sudo=""
    ip="192.168.0.252"
elif [[ $(hostname) == tegra-ubuntu ]]; then
    sudo="sudo"
    stream_ip="192.168.0.51"
    data_ip="192.168.0.255"
else
    echo "Unrecognized host"
    exit 1
fi
[[ $DEBUG -gt 0 ]] && make_args+=(DEBUG=1)

ulimit -c unlimited
set -x
make "${make_args[@]}" && $sudo env GST_DEBUG=${GST_DEBUG:-2} ./robot --thresh 0.001 --camera 0 --width 640 --height 480 --fps "15/1" --stream-fps "15/1" --ip "$stream_ip" --port 1190 --bitrate 750000 --data-ip "$data_ip" --broadcast cfg/obj.data cfg/tiny-yolo-obj2.cfg backup/tiny-yolo-obj2_4600.weights
